// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: links.sql

package dbgen

import (
	"context"
)

const countLinks = `-- name: CountLinks :one
SELECT COUNT(*) FROM links
`

func (q *Queries) CountLinks(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLinks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVisit = `-- name: CountVisit :one
UPDATE links
SET visit_count = visit_count + 1
WHERE code = ?
RETURNING code, url, visit_count, created_at
`

func (q *Queries) CountVisit(ctx context.Context, code string) (Link, error) {
	row := q.db.QueryRowContext(ctx, countVisit, code)
	var i Link
	err := row.Scan(
		&i.Code,
		&i.Url,
		&i.VisitCount,
		&i.CreatedAt,
	)
	return i, err
}

const createLink = `-- name: CreateLink :exec
INSERT INTO links (code, url, visit_count, created_at)
VALUES (?, ?, ?, ?)
`

type CreateLinkParams struct {
	Code       string
	Url        string
	VisitCount int64
	CreatedAt  string
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) error {
	_, err := q.db.ExecContext(ctx, createLink,
		arg.Code,
		arg.Url,
		arg.VisitCount,
		arg.CreatedAt,
	)
	return err
}

const deleteLink = `-- name: DeleteLink :execrows
DELETE FROM links WHERE code = ?
`

func (q *Queries) DeleteLink(ctx context.Context, code string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteLink, code)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getLink = `-- name: GetLink :one
SELECT code, url, visit_count, created_at
FROM links
WHERE code = ?
`

func (q *Queries) GetLink(ctx context.Context, code string) (Link, error) {
	row := q.db.QueryRowContext(ctx, getLink, code)
	var i Link
	err := row.Scan(
		&i.Code,
		&i.Url,
		&i.VisitCount,
		&i.CreatedAt,
	)
	return i, err
}

const listLinks = `-- name: ListLinks :many
SELECT code, url, visit_count, created_at
FROM links
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListLinksParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListLinks(ctx context.Context, arg ListLinksParams) ([]Link, error) {
	rows, err := q.db.QueryContext(ctx, listLinks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Link{}
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.Code,
			&i.Url,
			&i.VisitCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
