services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 3s
      retries: 10

  app:
    build: .
    environment:
      ADDR: ":8080"
      BASE_URL: "http://localhost:8080"
      DB_PATH: "/data/shortener.db"
      REDIS_ADDR: "redis:6379"
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy
