version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - misspell
    - unconvert
  exclusions:
    rules:
      # Generated code should not be linted.
      - path: api/gen.go
        linters:
          - revive
          - staticcheck
          - unused
