// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// CreateTweetRequest defines model for CreateTweetRequest.
type CreateTweetRequest struct {
	AuthorId string `json:"author_id"`
	Text     string `json:"text"`
}

// CreateUserRequest defines model for CreateUserRequest.
type CreateUserRequest struct {
	DisplayName *string `json:"display_name,omitempty"`
	Handle      string  `json:"handle"`
}

// Error defines model for Error.
type Error struct {
	Code    *string `json:"code,omitempty"`
	Message string  `json:"message"`
}

// Tweet defines model for Tweet.
type Tweet struct {
	AuthorHandle string    `json:"author_handle"`
	AuthorId     string    `json:"author_id"`
	CreatedAt    time.Time `json:"created_at"`
	Id           string    `json:"id"`
	Text         string    `json:"text"`
}

// TweetList defines model for TweetList.
type TweetList struct {
	Items []Tweet `json:"items"`

	// NextCursor Pass as before_id to fetch the next (older) page. Absent when there is no more.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// User defines model for User.
type User struct {
	CreatedAt     time.Time `json:"created_at"`
	DisplayName   string    `json:"display_name"`
	FollowerCount int64     `json:"follower_count"`
	Handle        string    `json:"handle"`

	// Id Snowflake id (string to avoid JS precision loss).
	Id string `json:"id"`
}

// BeforeId defines model for BeforeId.
type BeforeId = string

// Limit defines model for Limit.
type Limit = int

// GetHomeTimelineParams defines parameters for GetHomeTimeline.
type GetHomeTimelineParams struct {
	UserId string `form:"user_id" json:"user_id"`

	// BeforeId Keyset cursor; return tweets with id strictly less than this.
	BeforeId *BeforeId `form:"before_id,omitempty" json:"before_id,omitempty"`
	Limit    *Limit    `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListUserTweetsParams defines parameters for ListUserTweets.
type ListUserTweetsParams struct {
	// BeforeId Keyset cursor; return tweets with id strictly less than this.
	BeforeId *BeforeId `form:"before_id,omitempty" json:"before_id,omitempty"`
	Limit    *Limit    `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateTweetJSONRequestBody defines body for CreateTweet for application/json ContentType.
type CreateTweetJSONRequestBody = CreateTweetRequest

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = CreateUserRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Home timeline for a user (hybrid fan-out)
	// (GET /timelines/home)
	GetHomeTimeline(w http.ResponseWriter, r *http.Request, params GetHomeTimelineParams)
	// Post a tweet
	// (POST /tweets)
	CreateTweet(w http.ResponseWriter, r *http.Request)
	// Create a user
	// (POST /users)
	CreateUser(w http.ResponseWriter, r *http.Request)
	// Get a user by id
	// (GET /users/{id})
	GetUser(w http.ResponseWriter, r *http.Request, id string)
	// User {id} unfollows {targetId}
	// (DELETE /users/{id}/following/{targetId})
	Unfollow(w http.ResponseWriter, r *http.Request, id string, targetId string)
	// User {id} follows {targetId}
	// (PUT /users/{id}/following/{targetId})
	Follow(w http.ResponseWriter, r *http.Request, id string, targetId string)
	// A user's own tweets, newest first (pull)
	// (GET /users/{id}/tweets)
	ListUserTweets(w http.ResponseWriter, r *http.Request, id string, params ListUserTweetsParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Home timeline for a user (hybrid fan-out)
// (GET /timelines/home)
func (_ Unimplemented) GetHomeTimeline(w http.ResponseWriter, r *http.Request, params GetHomeTimelineParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Post a tweet
// (POST /tweets)
func (_ Unimplemented) CreateTweet(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a user
// (POST /users)
func (_ Unimplemented) CreateUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a user by id
// (GET /users/{id})
func (_ Unimplemented) GetUser(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// User {id} unfollows {targetId}
// (DELETE /users/{id}/following/{targetId})
func (_ Unimplemented) Unfollow(w http.ResponseWriter, r *http.Request, id string, targetId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// User {id} follows {targetId}
// (PUT /users/{id}/following/{targetId})
func (_ Unimplemented) Follow(w http.ResponseWriter, r *http.Request, id string, targetId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// A user's own tweets, newest first (pull)
// (GET /users/{id}/tweets)
func (_ Unimplemented) ListUserTweets(w http.ResponseWriter, r *http.Request, id string, params ListUserTweetsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHomeTimeline operation middleware
func (siw *ServerInterfaceWrapper) GetHomeTimeline(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetHomeTimelineParams

	// ------------- Required query parameter "user_id" -------------

	if paramValue := r.URL.Query().Get("user_id"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "user_id"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "user_id", r.URL.Query(), &params.UserId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	// ------------- Optional query parameter "before_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "before_id", r.URL.Query(), &params.BeforeId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "before_id", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHomeTimeline(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTweet operation middleware
func (siw *ServerInterfaceWrapper) CreateTweet(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTweet(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateUser operation middleware
func (siw *ServerInterfaceWrapper) CreateUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUser operation middleware
func (siw *ServerInterfaceWrapper) GetUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUser(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Unfollow operation middleware
func (siw *ServerInterfaceWrapper) Unfollow(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "targetId" -------------
	var targetId string

	err = runtime.BindStyledParameterWithOptions("simple", "targetId", chi.URLParam(r, "targetId"), &targetId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "targetId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Unfollow(w, r, id, targetId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Follow operation middleware
func (siw *ServerInterfaceWrapper) Follow(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "targetId" -------------
	var targetId string

	err = runtime.BindStyledParameterWithOptions("simple", "targetId", chi.URLParam(r, "targetId"), &targetId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "targetId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Follow(w, r, id, targetId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUserTweets operation middleware
func (siw *ServerInterfaceWrapper) ListUserTweets(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListUserTweetsParams

	// ------------- Optional query parameter "before_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "before_id", r.URL.Query(), &params.BeforeId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "before_id", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUserTweets(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/timelines/home", wrapper.GetHomeTimeline)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/tweets", wrapper.CreateTweet)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/users", wrapper.CreateUser)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/{id}", wrapper.GetUser)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/users/{id}/following/{targetId}", wrapper.Unfollow)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/users/{id}/following/{targetId}", wrapper.Follow)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/{id}/tweets", wrapper.ListUserTweets)
	})

	return r
}

type GetHomeTimelineRequestObject struct {
	Params GetHomeTimelineParams
}

type GetHomeTimelineResponseObject interface {
	VisitGetHomeTimelineResponse(w http.ResponseWriter) error
}

type GetHomeTimeline200JSONResponse TweetList

func (response GetHomeTimeline200JSONResponse) VisitGetHomeTimelineResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetHomeTimeline404JSONResponse Error

func (response GetHomeTimeline404JSONResponse) VisitGetHomeTimelineResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CreateTweetRequestObject struct {
	Body *CreateTweetJSONRequestBody
}

type CreateTweetResponseObject interface {
	VisitCreateTweetResponse(w http.ResponseWriter) error
}

type CreateTweet201JSONResponse Tweet

func (response CreateTweet201JSONResponse) VisitCreateTweetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateTweet400JSONResponse Error

func (response CreateTweet400JSONResponse) VisitCreateTweetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateTweet404JSONResponse Error

func (response CreateTweet404JSONResponse) VisitCreateTweetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CreateUserRequestObject struct {
	Body *CreateUserJSONRequestBody
}

type CreateUserResponseObject interface {
	VisitCreateUserResponse(w http.ResponseWriter) error
}

type CreateUser201JSONResponse User

func (response CreateUser201JSONResponse) VisitCreateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateUser400JSONResponse Error

func (response CreateUser400JSONResponse) VisitCreateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateUser409JSONResponse Error

func (response CreateUser409JSONResponse) VisitCreateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type GetUserRequestObject struct {
	Id string `json:"id"`
}

type GetUserResponseObject interface {
	VisitGetUserResponse(w http.ResponseWriter) error
}

type GetUser200JSONResponse User

func (response GetUser200JSONResponse) VisitGetUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetUser404JSONResponse Error

func (response GetUser404JSONResponse) VisitGetUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UnfollowRequestObject struct {
	Id       string `json:"id"`
	TargetId string `json:"targetId"`
}

type UnfollowResponseObject interface {
	VisitUnfollowResponse(w http.ResponseWriter) error
}

type Unfollow204Response struct {
}

func (response Unfollow204Response) VisitUnfollowResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type Unfollow404JSONResponse Error

func (response Unfollow404JSONResponse) VisitUnfollowResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type FollowRequestObject struct {
	Id       string `json:"id"`
	TargetId string `json:"targetId"`
}

type FollowResponseObject interface {
	VisitFollowResponse(w http.ResponseWriter) error
}

type Follow204Response struct {
}

func (response Follow204Response) VisitFollowResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type Follow400JSONResponse Error

func (response Follow400JSONResponse) VisitFollowResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type Follow404JSONResponse Error

func (response Follow404JSONResponse) VisitFollowResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ListUserTweetsRequestObject struct {
	Id     string `json:"id"`
	Params ListUserTweetsParams
}

type ListUserTweetsResponseObject interface {
	VisitListUserTweetsResponse(w http.ResponseWriter) error
}

type ListUserTweets200JSONResponse TweetList

func (response ListUserTweets200JSONResponse) VisitListUserTweetsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListUserTweets404JSONResponse Error

func (response ListUserTweets404JSONResponse) VisitListUserTweetsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Home timeline for a user (hybrid fan-out)
	// (GET /timelines/home)
	GetHomeTimeline(ctx context.Context, request GetHomeTimelineRequestObject) (GetHomeTimelineResponseObject, error)
	// Post a tweet
	// (POST /tweets)
	CreateTweet(ctx context.Context, request CreateTweetRequestObject) (CreateTweetResponseObject, error)
	// Create a user
	// (POST /users)
	CreateUser(ctx context.Context, request CreateUserRequestObject) (CreateUserResponseObject, error)
	// Get a user by id
	// (GET /users/{id})
	GetUser(ctx context.Context, request GetUserRequestObject) (GetUserResponseObject, error)
	// User {id} unfollows {targetId}
	// (DELETE /users/{id}/following/{targetId})
	Unfollow(ctx context.Context, request UnfollowRequestObject) (UnfollowResponseObject, error)
	// User {id} follows {targetId}
	// (PUT /users/{id}/following/{targetId})
	Follow(ctx context.Context, request FollowRequestObject) (FollowResponseObject, error)
	// A user's own tweets, newest first (pull)
	// (GET /users/{id}/tweets)
	ListUserTweets(ctx context.Context, request ListUserTweetsRequestObject) (ListUserTweetsResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetHomeTimeline operation middleware
func (sh *strictHandler) GetHomeTimeline(w http.ResponseWriter, r *http.Request, params GetHomeTimelineParams) {
	var request GetHomeTimelineRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHomeTimeline(ctx, request.(GetHomeTimelineRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHomeTimeline")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHomeTimelineResponseObject); ok {
		if err := validResponse.VisitGetHomeTimelineResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateTweet operation middleware
func (sh *strictHandler) CreateTweet(w http.ResponseWriter, r *http.Request) {
	var request CreateTweetRequestObject

	var body CreateTweetJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateTweet(ctx, request.(CreateTweetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateTweet")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateTweetResponseObject); ok {
		if err := validResponse.VisitCreateTweetResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateUser operation middleware
func (sh *strictHandler) CreateUser(w http.ResponseWriter, r *http.Request) {
	var request CreateUserRequestObject

	var body CreateUserJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateUser(ctx, request.(CreateUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateUserResponseObject); ok {
		if err := validResponse.VisitCreateUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetUser operation middleware
func (sh *strictHandler) GetUser(w http.ResponseWriter, r *http.Request, id string) {
	var request GetUserRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetUser(ctx, request.(GetUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetUserResponseObject); ok {
		if err := validResponse.VisitGetUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Unfollow operation middleware
func (sh *strictHandler) Unfollow(w http.ResponseWriter, r *http.Request, id string, targetId string) {
	var request UnfollowRequestObject

	request.Id = id
	request.TargetId = targetId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Unfollow(ctx, request.(UnfollowRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Unfollow")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UnfollowResponseObject); ok {
		if err := validResponse.VisitUnfollowResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Follow operation middleware
func (sh *strictHandler) Follow(w http.ResponseWriter, r *http.Request, id string, targetId string) {
	var request FollowRequestObject

	request.Id = id
	request.TargetId = targetId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Follow(ctx, request.(FollowRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Follow")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(FollowResponseObject); ok {
		if err := validResponse.VisitFollowResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListUserTweets operation middleware
func (sh *strictHandler) ListUserTweets(w http.ResponseWriter, r *http.Request, id string, params ListUserTweetsParams) {
	var request ListUserTweetsRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListUserTweets(ctx, request.(ListUserTweetsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListUserTweets")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListUserTweetsResponseObject); ok {
		if err := validResponse.VisitListUserTweetsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xYXXPbthL9Kzu4mbn2DCVKjnNvoj45nSZxmnYyjfPSjOuByaWIBAQYYGlZ1ei/dxag",
	"vixKjpPYjZ9EE9iPcw4OVpqJzFa1NWjIi9FM1NLJCgldeHqOhXV4mvPnHH3mVE3KGjESv+LUI0HWOG/d",
	"T+CQGmeAJojkYaKoBJWDJ6cy0lPQ6D1QKQ1QqXxfJEJxkM8NuqlIhJEVipG4DNkuVC4S4bMSK8l5aVrz",
	"S45lxmI+T8QbVSniV11BdHi5HiDHQjaaxOhokIhKXquqqcRoOOAnZdqnZJFHGcIxOjHnTDFIgOJnh5Lw",
	"jBv8Az836EMFtbM1OlIY1siGSuu4gdFM4LWsas0hh/9/OngyWP8biuRmX4kgvKbNjSVqbWFinWZIKnn9",
	"Bs2YSjE6ehqLXzwPkw6YHH5ulMNcjD6sVdbmOV/usJcfMSMuILb43qPb2WGufK3l9CKCvV7ra5l96uqq",
	"lCbXN9Z+jGtrSYSOOfzrw0nvT9n7e9B7dnE+GybDJ/NH4rae2shdnfzinHXb1Wc2xw5JJaJC7+UYu+W2",
	"nnOxsCtp0MZOUezBYaucb9NRFmjML2QoprCu4k8il4Q9UhV27bkt1fDo8ddIdj+YQY3rytyEqg2/0dBO",
	"3N+oLrkqwmrzwyOHhRiJ/6Qr20vbU55GAufLFNI5OeVng9d0Ea1u2wnfSu9Beli6F5CFAikrgUoE3gsH",
	"VufoDqGWY+zDyaVHQzApkf0QHYLyYCxU1mH/dtRCK11A8MntEP1XyOHux7ywWtsJuovMNmZTE8dHySqt",
	"MvS/Y7HttnuNYodcN3l4Z+yk0PIT8s1zENcyFfLKqhxev4PaYaa8sga09f6Qkb7j2erS71KsG5htAXKL",
	"ijm0MoXdbusEfCY19qxTaAhzOJsots2eVp8QPLorlSEUNms85mANlLaKxGplEApperahICtFodXflFGL",
	"KHDy9lQk4gqdj+kG/WF/wBDbGo2slRiJx/1B/3G06zIoKl1E9ykn43+No/Ox7iQXziODeIn0ylZ41q4O",
	"IVbTxYfu+7vx2LrBCmpyDe4dCbrP9SpbuhxkvmBtHC/m51yBr63x8RwdDQbxDjGEUeGyrrXKQr/pR8/w",
	"zdaKvNVpgmUF5m8yzjYBtgj+wQjDAnAm5nhw/N3qiPdkRw1sJZBbZF8iwOtYaiJ8U1XSTcVIvFqvCwrr",
	"QAJzBwfl9NKpfKG8w7AvjZNhcCfrO7SyNl611KOn5zaffrdeOwa4+eaJZpnNt1gffl/Wu9AOL6A1iMjx",
	"4P45PjVXUqsc3AKNB9LWSbjl96vrrfUEMn6fiAJibd2qn3AD3qd81ofjB1ZP6G3XUf0htPPs/vO+Crct",
	"SO1Q5lNQhj3nhnYiU60drYknnal8vu+yWqrnnlx/F4NnJba1PtAJ/N0SFLYx+Q3kXiItXPxyCirIqevK",
	"5klgdWPf8bI+3yQkjYOSMuN0RtKNkU4jSzlqJNwm6r2JO7aZOt6enmKnbQI4UDlWtWVkDx/O7iKge+0u",
	"nGFGA5q2Ow9raGzTsC0gmRG3yLmWv698E0/JbIdMw/ebUCSky3p35Fz0cDeFJKJuOo7oiy/n/cUezh/e",
	"HuEA++M+eNRFL8L1o8qvS3w3zutqkuv0UZ5qOd5ZXPYDDNGxkH/bWyMP//VgJ4vfSRMwOGF5FMqxSOpG",
	"68N78dz7+YIUGkR3taizcVqMRCprlV4N+f0/AQAA//+tPfXXXRYAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
